### ISSUE TITLE
Performance control

### ISSUE THREAD

**Issue by oliverellmers** [possiblecee/UnityVision-iOS#5]
Hello,

This is a very loose / broad question - 

From a high level - I was wondering if there are any ways of increasing performance?

Thanks in advance!

Oliver

**Comment by adamhegedues** [comment]
Hi,

This plugin does not block the main thread while evaluating image buffers. The default behaviour is that it performs as many evaluations as it possibly can, which is 10-15 per second on an iPhone 7, using InceptionV3. If you need more frequent observation results, you need to use a lighter ML model, or try to send a smaller image buffer for the plugin. Also, avoid creating a new CVPixelBuffer every time you run your evaluation. That API is not intended for real-time use. Provide a metal texture or a native buffer ptr (from the ARKit plugin) instead.

**Comment by oliverellmers** [comment]
Great thanks for the response!

Will look into the points you have discussed
