### ISSUE TITLE
Freezes up intermittently on only one iPhone

### ISSUE THREAD

**Issue by CharStiles** [possiblecee/UnityVision-iOS#6]
Hello,
The classification app works on many phones but on one iPhone XS it freezes up. I was wondering if anyone had some ideas why. 

So here are the details:
iOS:12.2
The behavior is that it works for a few seconds then it freezes for 1-2 seconds and it works again, and this freezing continues. 

I turned on Zombie Objects and get many of this error from the devices simulator console whenever it freezes
`2019-03-20 12:58:34.740735-0400 snobBog3[7837:2621978] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)`
I noticed I also get this warning before
`Tiled GPU perf. warning: RenderTexture color surface (1080x1920) was not cleared/discarded.`

The problem is definitely is somewhere in the classification code, because all the AR stuff works when the vision script is disabled.

I have tried (that I can remember):
- updating swift version to newest version
- getting rid of all unnecessary shaders
- lowering the maxClassificationResults (trying to not overload the GPU)
- updating iphone system/closing all other apps/reinstalling etc

I tested it on a different iPhone XS and it works great. 

I have never developed an app before that deals with swift or CoreML so anything you may seem as obvious to try may save me more weeks of headaches! Is there something I should be looking at that would tell me why it works on one iPhoneXS but not another?

Thanks for reading I anticipate & appreciate a response

**Comment by adamhegedues** [comment]
Hi CharStiles,

Could you please let me know how do you create or pass the CVPixelBuffer to the native component? I had this issue before when I used Metal textures on iOS 12.0 and it turned out to be a driver bug. 

"I tested it on a different iPhone XS and it works great."

Are both of those iPhone on the same iOS version?

Best regards,
Adam

**Comment by CharStiles** [comment]
Thank you for your fast response! 

- I haven't changed any of the code in this repo that much, I am using it as is. Sorry if I am not understanding your question correctly!
- How did you solve the driver bug (if there is a solution)?
- If I remember correctly they were the same iOS version, but I inquired the owner of said phone to make sure.

Char

**Comment by adamhegedues** [comment]
Hi,

I meant what example did you base your app on? There are 2 ARKit examples included in this repo.

Thanks,
Adam

**Comment by CharStiles** [comment]
You mean classification vs rectangle? I mentioned I am using the classification example. Sorry I should have made that more clear :)

**Comment by adamhegedues** [comment]
There are actually 4 examples for classification. Two of them use ARKit. :)

**Comment by CharStiles** [comment]
Ah! My apologies! I am using the first one (ARKitExample.cs), my bad I didn't realize there was a difference.

**Comment by adamhegedues** [comment]
I pushed a change yesterday. The only file that's been modified is this:
UnityVision-iOS/Assets/Scripts/Possible/Vision/Plugins/iOS/VisionNative.swift

Can you please pull and try to see if your problem persists? If this doesn't solve the issue, try using the second example. 

Also, did you find out the version numbers on those iPhones?

**Comment by CharStiles** [comment]
Hi Adam, 
I had a meeting with the person with the problematic iPhone, and THANK YOU the new script worked like a charm!

The version number is A1920. Also I mentioned a while back that I inquired if the other non-problematic iPhone XS had the same iOS version, he said he doesnt remember, alas. 

So my naive stab at what you have done is replace the buffer that holds the pixels from the camera from ciImage to cvPixelBuffer? I am in awe at how quickly and efficiently you solved my problem. 

Thank you again,

Char
